spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fruitwarehouse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: fruitwarehouse
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    liquibase-schema: public
    default-schema: fruitwarehouse
    change-log: classpath:/db/changelog/db.changelog-master.yaml
